config/routes.rb
CricketWorld::Application.routes.draw do
  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'leagues#show', :id=>4
  
  resources :matches do
    member do
      get :upload_lineup
      patch :save_lineup
      get :upload_toss
      patch :save_toss
      get :upload_inning
      patch :save_inning
    end
  end
  
  resources :leagues
  resources :teams do
    member do
      get :players
      get :matches
    end
    collection do 
      get :forum
      get :public_forum
    end
  end
  resources :players

  

end

app/models/league.rb
class League < ActiveRecord::Base
	has_many :league_statuses, :dependent => :delete_all
	
  accepts_nested_attributes_for :league_statuses, allow_destroy: true, :reject_if => proc { |attributes| attributes['team_id'].blank? }

  validates_presence_of :name, :description
end

app/controllers/leagues_controller.rb
class LeaguesController < ApplicationController
  def index
  end
  
  def show
    @league = League.find(params[:id])
    render 'tournament'
  end
end

app/views/leagues/show.html.erb
<div class="league_header2"><h1><%= @league.name; %></span></h1></div>

<div class="league_infobar clearfix">
	<!--<div class="all_records">
		<ul>
			<li>
				<%= link_to("Most Runs", ''); %>
				<img src="<%= asset_path('small_black_star.png') %>" />
			</li>
			<li>
				<%= link_to("Best Batting Average", ''); %>
				<img src="<%= asset_path('small_black_star.png') %>" />
			</li>
			<li>
				<%= link_to("Highest Score", ''); %>
				<img src="<%= asset_path('small_black_star.png') %>" />
			</li>
			<li>
				<%= link_to("Most Wickets", ''); %>
				<img src="<%= asset_path('small_black_star.png') %>" />
			</li>
			<li>
				<%= link_to("Best Bowling Average", ''); %>
				<img src="<%= asset_path('small_black_star.png') %>" />
			</li>
			<li>
				<%= link_to("Best Bowling Figures", ''); %>
				<img src="<%= asset_path('small_black_star.png') %>" />
			</li>
			<li>
				<%= link_to("Best Economy", ''); %>
			</li>
		</ul>
	</div>-->
</div>
<br clear="all" />

<div class="padit">
	<div class="row-fluid">
		<div class="span12">
			<div class="">
				<table class="table table-striped league_table">
					<thead>
						<tr>
							<th align="left" width="10">#</th>
							<th align="left">Team</th>
							<th style="text-align:center">Played</th>
							<th style="text-align:center">Points</th>
							<th style="text-align:center">Wins</th>
							<th style="text-align:center">Loss</th>
							<th style="text-align:center">Ties</th>
							<th style="text-align:center">Net R.R.</th>
						</tr>   
					</thead>     

					<% @league.league_statuses.each do |league_status| %>
					<tr>
						<td><%= league_status.position; %></td>
						<td><%= link_to league_status.team.name, team_path(league_status.team); %></td>
						<td style="text-align:center"><%= league_status.matches_played; %></td>
						<td style="text-align:center"><%= league_status.points; %></td>
						<td style="text-align:center"><%= league_status.wins; %></td>
						<td style="text-align:center"><%= league_status.losses; %></td>
						<td style="text-align:center"><%= league_status.ties; %></td>
						<td style="text-align:center"><%= league_status.run_rate.blank? ? 0.00 : league_status.run_rate; %></td>
					</tr>
					<% end %>
				</table>
			</div>

			<div class="m30">
				<ul class="player_matches">
				<% Match.all.each do |match| %>
					<li class="league">
						<span class="match_date">
							<span class="date"><%= match.start_time.strftime('%d') %></span>
							<span class="month"><%= match.start_time.strftime('%b') %></span>
						</span>

						<%= render :partial => '/matches/result_string', :locals => {match: match} %>
						<br clear="all" />
					</li>
				<% end %>
				</ul>

			</div>
			
		</div> <!--end span12 -->
		<br clear="all" />
	</div>
</div>

app/views/leagues/tournament.html.erb
<div class="league_header2"><h1><%= @league.name; %></span></h1></div>

<div class="league_infobar clearfix">
	<!--<div class="all_records">
		<ul>
			<li>
				<%= link_to("Most Runs", ''); %>
				<img src="<%= asset_path('small_black_star.png') %>" />
			</li>
			<li>
				<%= link_to("Best Batting Average", ''); %>
				<img src="<%= asset_path('small_black_star.png') %>" />
			</li>
			<li>
				<%= link_to("Highest Score", ''); %>
				<img src="<%= asset_path('small_black_star.png') %>" />
			</li>
			<li>
				<%= link_to("Most Wickets", ''); %>
				<img src="<%= asset_path('small_black_star.png') %>" />
			</li>
			<li>
				<%= link_to("Best Bowling Average", ''); %>
				<img src="<%= asset_path('small_black_star.png') %>" />
			</li>
			<li>
				<%= link_to("Best Bowling Figures", ''); %>
				<img src="<%= asset_path('small_black_star.png') %>" />
			</li>
			<li>
				<%= link_to("Best Economy", ''); %>
			</li>
		</ul>
	</div>-->
</div>
<br clear="all" />

<div class="padit">
	<div class="row-fluid">
		<div class="span12">
			<div class="span5">
				<table class="table table-striped league_table">
					<thead>
						<tr>
							<th align="left" width="10">&nbsp;</th>
							<th align="left">Team</th>
						</tr>   
					</thead>     
					<% Team.all.each do |team| %>
					<tr>
						<td>&nbsp;</td>
						<td><%= link_to team.name, team_path(team); %></td>
					</tr>
					<% end %>
				</table>
			</div>

			<div class="span6 offset1">
				<ul class="player_matches">
				<% Match.all.each do |match| %>
					<li class="league">
						<span class="match_date">
							<span class="date"><%= !match.start_time.blank? ? match.start_time.strftime('%d') : '' %></span>
							<span class="month"><%= !match.start_time.blank? ? match.start_time.strftime('%b') : '' %></span>
						</span>

						<%= render :partial => '/matches/result_string', :locals => {match: match} %>
						<br clear="all" />
					</li>
				<% end %>
				</ul>

			</div>
			
		</div> <!--end span12 -->
		<br clear="all" />
	</div>
</div>