config/routes.rb
CricketWorld::Application.routes.draw do
  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'leagues#show', :id=>4
  
  resources :matches do
    member do
      get :upload_lineup
      patch :save_lineup
      get :upload_toss
      patch :save_toss
      get :upload_inning
      patch :save_inning
    end
  end
  
  resources :leagues
  resources :teams do
    member do
      get :players
      get :matches
    end
    collection do 
      get :forum
      get :public_forum
    end
  end
  resources :players

  

end

app/models/player.rb
class Player < ActiveRecord::Base
  belongs_to :user
  belongs_to :team
  
  validates_presence_of :team_id
  
  scope :filter_team, lambda {|team_id| where("team_id = ?", team_id)}
  
  def name
    return user.name
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController  
  def show
    @player = Player.find(params[:id])
  end
end

app/views/admin/players/create_users.html.erb
<% 10.times {current_admin_user.users.build} %>

<%= semantic_form_for(current_admin_user, :url=>admin_admin_user_path(current_admin_user), builder: ActiveAdmin::FormBuilder) do |f| %>

  <%= f.semantic_errors *f.object.errors.keys %>

  <%= f.semantic_fields_for :users, :allow_destroy => true do |user_form| %>
    <% if !user_form.object.persisted? %>

      <div class="has_many_container users">
        <fieldset class="inputs has_many_fields">
        <ol>
          
            <%= user_form.input :name %>
            <%= user_form.input :email %>
            <%= user_form.input :age %>
            <%= user_form.input :height %>
            <%= user_form.input :batting_style %>
            <%= user_form.input :bowling_style %>

            <% temp_pwd = User.get_random_temporary_password %>
            <%= user_form.input :password, :as => :hidden, :input_html => { :value => temp_pwd }  %>
            <%= user_form.input :password_confirmation, :as => :hidden, :input_html => { :value => temp_pwd }  %>

            <% user_form.object.players.build %>
            
          	<%= user_form.semantic_fields_for :players, :allow_destroy =>true do |q| %>
          		<%= q.input :team, :collection => Team.all.map {|team| [team.name, team.id]} %>
          	<% end %>	
          
        </ol>
        </fieldset>
      </div>

    <% end %>
  <% end %>

  <%= f.actions do %>
    <%= f.action :submit, label: 'Save Players' %>
  <% end %>
<% end %>