config/routes.rb
CricketWorld::Application.routes.draw do
  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'leagues#show', :id=>4
  
  resources :matches do
    member do
      get :upload_lineup
      patch :save_lineup
      get :upload_toss
      patch :save_toss
      get :upload_inning
      patch :save_inning
    end
  end
  
  resources :leagues
  resources :teams do
    member do
      get :players
      get :matches
    end
    collection do 
      get :forum
      get :public_forum
    end
  end
  resources :players

  

end

app/views/shared/_top_big_nav.html.erb
<div id="team_nav">
        <div class="container" >
                <div class="row">
                        <div class="span3">
                                <p style="margin-top:20px;"><%= link_to(image_tag("mad_logo.png"), league_path(4)) %></p>
                        </div><!--end 3 -->
                        <div class="span9">
                                <div class="pull-right"><%= link_to(image_tag("logo2.png"), "http://hitwicket.com", :target=>'_blank') %></div>
                        </div>
                </div>
        </div>
</div>

app/views/shared/_top_nav.html.erb
<div id="sticky-anchor-nav"></div>
<div id="sticky-nav">
	<!--<div class="navbar">
		<div class="navbar-inner">
			<div class="container" style="width:1170px">
				<div class="nav-collapse">
					<div class="orange-bar">
						<ul class="nav">
							<li class="dropdown">
								<a class="dropdown-toggle main" data-toggle="dropdown" href="#">Notifications <span class="count">2</span></a>
								<ul class="dropdown-menu wide_drop_menu notifications_top" id="notification_dropdown_ul">
									<li class="">
										<a class="notification_link" data="5561316" href="/league/show/4">Nikhil2824 has posted in the Forum.</a>	
										<span class="time ml10">15 minutes ago</span>
										<br clear="all">
									</li>
									<li class="">
										<a class="notification_link" data="5555201" href="/league/show/4?message_id=181715">Ishan has tagged you in a Foorum post.</a>	
										<span class="time ml10">8 hours ago</span>
										<br clear="all">
									</li>
								</ul>
							</li>
							<li class=""><%= link_to('Team Forum', forum_teams_path, :class=>'main'); %></li>
							<li class=""><%= link_to('Public Forum', public_forum_teams_path, :class=>'main'); %></li>
						</ul>						
						<ul class="nav pull-right">                 
							<li class="dropdown" id="menu1">
								<a class="dropdown-toggle main settings_link" data-toggle="dropdown" href="#">
									<%= image_tag("settings.png") %>
								</a>
								<ul class="dropdown-menu">									
									<li><%= link_to('Update Profile', '') %></li>
									<li><a href="#">Logout</a></li>
								</ul>
							</li>
						</ul>
						<div id="top_username" title="">Hello, John Doe</div>
					</div>
				</div>
			</div>
		</div>
	</div>-->
</div>