config/routes.rb
CricketWorld::Application.routes.draw do
  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'leagues#show', :id=>4
  
  resources :matches do
    member do
      get :upload_lineup
      patch :save_lineup
      get :upload_toss
      patch :save_toss
      get :upload_inning
      patch :save_inning
    end
  end
  
  resources :leagues
  resources :teams do
    member do
      get :players
      get :matches
    end
    collection do 
      get :forum
      get :public_forum
    end
  end
  resources :players

  

end

app/models/match.rb
class Match < ActiveRecord::Base
  
  STATUS_INITIALIZED = 1;
  STATUS_SCORED_ENTERED = 2;
  STATUSES = { self::STATUS_INITIALIZED => 'Pending',  self::STATUS_SCORED_ENTERED => 'Score Updated' }
  
  belongs_to :home_team, :class_name=>'Team', :foreign_key=>'home_team_id'
  belongs_to :away_team, :class_name=>'Team', :foreign_key=>'away_team_id'
  has_one :match_result, :dependent => :delete
  has_many :match_innings, :dependent => :delete_all
  has_many :match_players, :dependent => :delete_all
  has_many :match_performances, :dependent => :delete_all
  
  #sti
  has_many :team_a_match_players
  has_many :team_b_match_players
  has_one :first_match_inning
  has_one :second_match_inning
    
  validates_presence_of :home_team_id, :away_team_id
  accepts_nested_attributes_for :match_result, :team_a_match_players, :team_b_match_players, :first_match_inning, :second_match_inning, :match_performances
  before_save :default_status
  just_define_datetime_picker :start_time

  #after_save :update_innings_data

  PLAYERS = 7
  
  def default_status
    self.status = STATUS_INITIALIZED
  end
  
  def create_innings
    if(!self.first_match_inning)
      self.build_first_match_inning({:team_id=>match_result.first_batting_team_id, :number=>1})
      self.first_match_inning.save
      first_batting_players.each_with_index do |match_player, index|
        self.match_performances.create({:team_id=>match_result.first_batting_team_id, :batting_position=>(index+1), :bowling_position=>(index+1)})
      end
    end
    if(!self.second_match_inning)
      self.build_second_match_inning({:team_id=>match_result.second_batting_team_id, :number=>2})
      self.second_match_inning.save
      second_batting_players.each_with_index do |match_player, index|
        self.match_performances.create({:team_id=>match_result.second_batting_team_id, :batting_position=>(index+1), :bowling_position=>(index+1)})
      end
    end
  end
  
  def first_batting_team
    if !match_result
      return NULL
    else
      return Team.find(match_result.first_batting_team_id)
    end
  end

  def second_batting_team
    if !match_result
      return NULL
    else
      return Team.find(match_result.second_batting_team_id)
    end
  end
  
  def first_batting_performances
    if(match_result.first_batting_team_id)
      return self.match_performances.filter_team(match_result.first_batting_team_id)
    else
      return NULL
    end
  end
  
  def second_batting_performances
    if(match_result.second_batting_team_id)
      return self.match_performances.filter_team(match_result.second_batting_team_id)
    else
      return NULL
    end
  end
  
  def first_batting_players
    if(match_result.first_batting_team_id)
      return self.match_players.filter_team(match_result.first_batting_team_id)
    else
      return NULL
    end
  end
  
  def second_batting_players
    if(match_result.first_batting_team_id)
      return self.match_players.filter_team(match_result.second_batting_team_id)
    else
      return NULL
    end
  end
  
  def home_team_inning
    match_innings.filter_team(home_team_id).first
  end
  
  def away_team_inning
    match_innings.filter_team(away_team_id).first
  end
  
  def get_opponent_team_id(team_id)
    if(home_team_id == team_id)
      return away_team_id
    else
      return home_team_id 
    end
  end
  
  def get_title
    if home_team_inning && away_team_inning
		  #return "#{home_team.name} <span class='result_score'>#{home_team_inning.runs}/#{home_team_inning.wickets} <span>#{home_team_inning.overs}</span></span> v #{away_team.name} <span class='result_score'>#{away_team_inning.runs}/#{away_team_inning.wickets} <span>#{away_team_inning.overs}</span></span>"
      return "#{home_team.name} v #{away_team.name}"
		else
		  return "#{home_team.name} v #{away_team.name}"
		end
  end

  def update_innings_data
    if !away_team_inning.blank? and !home_team_inning.blank? and !match_performances.blank?
      if home_team_id == match_result.second_batting_team_id
        self.home_team_inning.runs = first_batting_performances.map{|m| m.runs_scored.to_i}.inject(&:+)
        self.home_team_inning.wickets = first_batting_performances.where("mode_of_dismissal is not null and mode_of_dismissal != ''").length
        self.home_team_inning.balls = first_batting_performances.map{|m| m.balls_faced.to_i}.inject(&:+)

        self.away_team_inning.runs = second_batting_performances.map{|m| m.runs_scored.to_i}.inject(&:+)
        self.away_team_inning.wickets = second_batting_performances.where("mode_of_dismissal is not null and mode_of_dismissal != ''").length
        self.away_team_inning.balls = second_batting_performances.map{|m| m.balls_faced.to_i}.inject(&:+)
      else
        self.away_team_inning.runs = first_batting_performances.map{|m| m.runs_scored.to_i}.inject(&:+)
        self.away_team_inning.wickets = first_batting_performances.where("mode_of_dismissal is not null and mode_of_dismissal != ''").length
        self.away_team_inning.balls = first_batting_performances.map{|m| m.balls_faced.to_i}.inject(&:+)

        self.home_team_inning.runs = second_batting_performances.map{|m| m.runs_scored.to_i}.inject(&:+)
        self.home_team_inning.wickets = second_batting_performances.where("mode_of_dismissal is not null and mode_of_dismissal != ''").length
        self.home_team_inning.balls = second_batting_performances.map{|m| m.balls_faced.to_i}.inject(&:+)
      end
      self.home_team_inning.save
      self.away_team_inning.save
    end
  end

  def scores
    home_team_runs = home_team_wickets = home_team_balls = away_team_runs = away_team_wickets = away_team_balls = 0
    if !away_team_inning.blank? and !home_team_inning.blank? and !match_performances.blank?
      if home_team_id == match_result.second_batting_team_id
        home_team_runs = first_batting_performances.map{|m| m.runs_scored.to_i}.inject(&:+)
        home_team_wickets = first_batting_performances.where("mode_of_dismissal is not null and mode_of_dismissal != ''").length
        home_team_balls = first_batting_performances.map{|m| m.balls_faced.to_i}.inject(&:+)

        away_team_runs = second_batting_performances.map{|m| m.runs_scored.to_i}.inject(&:+)
        away_team_wickets = second_batting_performances.where("mode_of_dismissal is not null and mode_of_dismissal != ''").length
        away_team_balls = second_batting_performances.map{|m| m.balls_faced.to_i}.inject(&:+)
      else
        home_team_runs = first_batting_performances.map{|m| m.runs_scored.to_i}.inject(&:+)
        home_team_wickets = first_batting_performances.where("mode_of_dismissal is not null and mode_of_dismissal != ''").length
        home_team_balls = first_batting_performances.map{|m| m.balls_faced.to_i}.inject(&:+)

        away_team_runs = second_batting_performances.map{|m| m.runs_scored.to_i}.inject(&:+)
        away_team_wickets = second_batting_performances.where("mode_of_dismissal is not null and mode_of_dismissal != ''").length
        away_team_balls = second_batting_performances.map{|m| m.balls_faced.to_i}.inject(&:+)
      end
    end
    return [home_team_runs , home_team_wickets , home_team_balls , away_team_runs , away_team_wickets , away_team_balls]
  end
  
  scope :initialized, lambda { where(:status => STATUS_INITIALIZED) }
  scope :played_by_team, lambda { |team_id| where("home_team_id = #{team_id} or away_team_id = #{team_id}") }
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  
  #permit_params match_player_attributes: [:player_id, :_destroy]
  
  def index
    @matches = Match.initialized.all
  end
  
  def show
    @match = Match.find(params[:id])
  end
  
  def upload_lineup
    @match = Match.find(params[:id])
    if @match.team_a_match_players.length < Match::PLAYERS
      Match::PLAYERS.times { @match.team_a_match_players.build }
    end
    if @match.team_b_match_players.length < Match::PLAYERS
      Match::PLAYERS.times { @match.team_b_match_players.build }
    end
  end
  
  def save_lineup    
    match = Match.find(params[:id])
    match.update_attributes(match_params)
    match.save
    redirect_to upload_toss_match_path(match)
  end
  
  def upload_toss
    @match = Match.find(params[:id])
    @match.build_match_result
  end
  
  def save_toss
    match = Match.find(params[:id])
    match.update_attributes(match_params)
    match.save
    redirect_to upload_inning_match_path(match, {:number=>1})
  end
  
  def upload_inning
    @match = Match.find(params[:id])
    @match.create_innings
    if params[:number].to_i == 1
      @innings = @match.match_innings.where("number = #{params[:number]}").first
      @team = @match.first_batting_team
      @bowling_team = @match.second_batting_team
      @batting_performances = @match.first_batting_performances
      @bowling_performances = @match.second_batting_performances
      @batting_players = @match.first_batting_players
      @bowling_players = @match.second_batting_players
      @url = save_inning_match_path(@match, {:number =>2})
    else
      @innings = @match.match_innings.where("number = #{params[:number]}").first
      @team = @match.second_batting_team
      @bowling_team = @match.first_batting_team
      @batting_performances = @match.second_batting_performances
      @bowling_performances = @match.first_batting_performances
      @batting_players = @match.second_batting_players
      @bowling_players = @match.first_batting_players
      @url = save_inning_match_path(@match)
    end

  end
  
  def save_inning
    match = Match.find(params[:id])
    match.attributes = match_params
    match.save
    #match.update_innings_data
    flash[:success] = "Innings data saved!"
    if params.has_key?("number")
      redirect_to upload_inning_match_path(match, {:number=>2})
    else
      redirect_to match_path(match)
      #redirect_to upload_inning_match_path(match, {:number=>2})
    end
  end
  
  private
  
  def match_params
    params.require(:match).permit(
      :home_team_id, :away_team_id, 
      team_a_match_players_attributes:[:player_id, :team_id], 
      team_b_match_players_attributes:[:player_id, :team_id], 
      match_result_attributes:[:toss_winner_team_id, :toss_choice],
      match_performances_attributes:[:id, :player_id, :team_id, :batting_position, :runs_scored, :balls_faced, :fours, :sixes, :mode_of_dismissal, :bowling_position, :balls_bowled, :runs_conceded, :wickets]
    )
  end
end

app/helpers/matches_helper.rb
module MatchesHelper
  def get_match_title(match)
    match.home_team.name+' vs '+match.away_team.name
  end
end

app/views/matches/_header.html.erb
<% scores = @match.scores %>
<section class="match_summary">
<div class="match_header" id="match_header_banner">
   <div class="left_team">
	    <span class="team_name"><%= link_to @match.home_team.name, @match.home_team %></span>
	    <span class="current_score">
	        <span class="current_total" id="home_total_in_match_header_banner"><%= scores[0] %>/<%= scores[1] %></span>
	        <span class="current_over" id="home_overs_in_match_header_banner"><%= MatchInning.return_overs(scores[2]) %></span>
	    </span>
	</div>
	<div class="center_team">
	-
	</div>
	<div class="right_team">
	    <span class="current_score">
	        <span class="current_total" id="away_total_in_match_header_banner"><%= scores[3] %>/<%= scores[4] %></span>
	        <span class="current_over" id="away_overs_in_match_header_banner"><%= MatchInning.return_overs(scores[5]) %></span>
	    </span>
	    <span class="team_name"><%= link_to @match.away_team.name, @match.away_team %></span>
	</div>
</div>
</section>
<br />
<div class="tac">
	<%= @match.description %>
</div>

app/views/matches/_inning.html.erb
<div style="margin-top:20px;">
	<h2><%= team.name %> (<%= total_runs %>/<%= total_wickets %> in <%= MatchInning.return_overs(total_balls) %>)</h2><br />
	<table class="table table-striped table-hovered table-bordered" style="width: 80%;">
		<tr>
			<th>#</th>
			<th style="width: 20%;">Batsman</th>
			<th>&nbsp;</th>
			<th>Runs</th>
			<th>Balls</th>
			<th>Fours</th>
			<th>Sixes</th>
		</tr>
		<% batting_performances.order('batting_position').each do |batting_performance| %>
			<% if !batting_performance.runs_scored.blank? %>
				<tr>
					<td><%= batting_performance.batting_position %></td>
					<td><%= batting_performance.player.user.name %></td>
					<td><%= batting_performance.mode_of_dismissal %></td>
					<td><%= batting_performance.runs_scored %></td>
					<td><%= batting_performance.balls_faced %></td>
					<td><%= batting_performance.fours %></td>
					<td><%= batting_performance.sixes %></td>
				</tr>
			<% end %>
		<% end %>
	</table>

	<table class="table table-striped table-hovered table-bordered" style="width: 50%;">
		<tr>
			<th>Bowler</th>
			<th>Overs</th>
			<th>Runs</th>
			<th>Wickets</th>
		</tr>
		<% bowling_performances.each do |bowling_performance| %>
			<% if !bowling_performance.balls_bowled.blank? %>
				<tr>
					<td><%= bowling_performance.player.user.name %></td>
					<td><%= bowling_performance.balls_bowled %></td>
					<td><%= bowling_performance.runs_conceded %></td>
					<td><%= bowling_performance.wickets %></td>
				</tr>
			<% end %>
		<% end %>
	</table>
</div>
<br />

app/views/matches/_result_string.html.erb
<%= link_to(raw(match.get_title), match_path(match), :class=>'match'); %>

<br /><span class="result_net"><%= "" %></span>

app/views/matches/index.html.erb
<ul>
<% @matches.each do |match| %>
	<li>
		<%= get_match_title(match) %>
		<%= link_to "Update Scores", upload_lineup_match_path(match) %>
	</li>
<% end %>
</ul>

app/views/matches/show.html.erb
<%= render :partial => 'header' %>
<div class="padit">
	<% if !@match.away_team_inning.blank? and !@match.home_team_inning.blank? and !@match.match_performances.blank? %>
	<% scores = @match.scores %>
	<%= render :partial => 'inning', :locals => { batting_performances: @match.first_batting_performances, bowling_performances: @match.second_batting_performances, team: @match.first_batting_team, total_runs: scores[0], total_wickets: scores[1], total_balls: scores[2] } %>
	<p class="divider"></p>
	<%= render :partial => 'inning', :locals => { batting_performances: @match.second_batting_performances, bowling_performances: @match.first_batting_performances, team: @match.second_batting_team, total_runs: scores[3], total_wickets: scores[4], total_balls: scores[5] } %>
	<% end %>
</div>

app/views/matches/upload_inning.erb
<%= render :partial => 'header' %>
<div class="padit">
	<h1>Inning <%= @innings.number %></h1>
	<% if @innings.number.to_i == 2  %>
		<%= link_to "Innings 1", upload_inning_match_path(@match, {:number =>1}), class: 'btn btn-info btn-medium fr' %>
	<% end %>
	<%= nested_form_for(@match, url: @url) do |f| %>
		<h4 class="sub_head"><%= @team.name %>  - Batting</h4>
		<table class="table table-striped table-hovered">
			<tr>
				<th>Position</th>
				<th>Batsman</th>
				<th style="width:20%">Mode of Dismissal</th>
				<th>Runs</th>
				<th>Balls</th>
				<th>Fours</th>
				<th>Sixes</th>
			</tr>
			<%= f.fields_for :match_performances, @batting_performances do |batting_performance| %>
				<tr>
					<%= batting_performance.hidden_field(:batting_position) %>
					<%= batting_performance.hidden_field(:team_id) %>
					<td class='position'><%= batting_performance.object.batting_position %></td>
					<td><%= batting_performance.collection_select(:player_id, @batting_players, :player_id, :player_name, :class=>'scorecard_field') %></td>
					<td style="width:20%"><%= batting_performance.text_field(:mode_of_dismissal) %></td>
					<td><%= batting_performance.text_field(:runs_scored, :class=>'scorecard_field') %></td>
					<td><%= batting_performance.text_field(:balls_faced, :class=>'scorecard_field') %></td>
					<td><%= batting_performance.text_field(:fours, :class=>'scorecard_field') %></td>
					<td><%= batting_performance.text_field(:sixes, :class=>'scorecard_field') %></td>
				</tr>
			<% end %>
		</table>
		
		<h4 class="sub_head"><%= @bowling_team.name %> - Bowling</h4>
		<table class="table table-striped table-hovered">
			<tr>
				<th>Bowler</th>
				<th>Overs</th>
				<th>Runs</th>
				<th>Wickets</th>
			</tr>
			<%= f.fields_for :match_performances, @bowling_performances do |bowling_performance| %>
				<tr>
					<%= bowling_performance.hidden_field(:bowling_position) %>
					<%= bowling_performance.hidden_field(:team_id) %>
					<td><%= bowling_performance.collection_select(:player_id, @bowling_players, :player_id, :player_name, :class=>'scorecard_field') %></td>
					<td><%= bowling_performance.text_field(:balls_bowled, :class=>'scorecard_field', :value=>MatchInning.return_overs_without_string(bowling_performance.object.balls_bowled)) %></td>
					<td><%= bowling_performance.text_field(:runs_conceded, :class=>'scorecard_field') %></td>
					<td><%= bowling_performance.text_field(:wickets, :class=>'scorecard_field') %></td>
				</tr>
			<% end %>
		</table>	
		<%= f.submit "Save", class: 'btn btn-success btn-large' %>
	<% end %>
</div>

app/views/matches/upload_lineup.html.erb
<%= render :partial => 'header' %>
<div class="padit tac">
	<%= nested_form_for(@match, url: {action: "save_lineup"}) do |f| %>

		<div class="span12">
			<div class="span5">
				<h4 class="sub_head"><%= @match.home_team.name %> Squad</h4>
				<% players = Player.filter_team(@match.home_team_id) %>
				<% i = 0 %>
				<%= f.fields_for :team_a_match_players do |match_player| %>
					<%= match_player.hidden_field(:team_id, :value =>@match.home_team_id) %>
					<% if !match_player.object.player_id.blank? %>
						<%= match_player.collection_select(:player_id, players, :id, :name,) %>
					<% else %>
						<%= match_player.collection_select(:player_id, players, :id, :name, :selected =>players[i].id) %>
					<% end %>
					<% i = i + 1 %>
				<% end %>
			</div>

			<div class="span5">		
				<h4 class="sub_head"><%= @match.away_team.name %> Squad</h4>
				<% players = Player.filter_team(@match.away_team_id) %>
				<% i = 0 %>
				<%= f.fields_for :team_b_match_players do |match_player| %>
					<%= match_player.hidden_field(:team_id, :value =>@match.away_team_id) %>
					<% if !match_player.object.player_id.blank? %>
						<%= match_player.collection_select(:player_id, players, :id, :name,) %>
					<% else %>
						<%= match_player.collection_select(:player_id, players, :id, :name, :selected =>players[i].id) %>
					<% end %>
					<% i = i + 1 %>
				<% end %>
			</div>
			<br clear="all" />
		</div><br clear="all" /><br />
		<%= f.submit "Save", class: 'btn btn-success btn-large' %>
	<% end %>
</div>

app/views/matches/upload_toss.html.erb
<%= render :partial => 'header' %>
<div class="padit">
	<%= nested_form_for(@match, url: {action: "save_toss"}) do |f| %>
		<%= f.fields_for :match_result do |match_player| %>
			<h4 class="sub_head">Toss Winner</h4>		
			<%= match_player.collection_select(:toss_winner_team_id, [@match.home_team, @match.away_team], :id, :name) %>
			<br /><br />
			<h4 class="sub_head">Choice</h4>		
			<%= match_player.select(:toss_choice, MatchResult::TOSS_CHOICES) %>
		<% end %>
		<br />
		<%= f.submit "Save", class: 'btn btn-success btn-large' %>
	<% end %>
</div>